Chips , snackbar cmponent added + code samples in all components
rishichourasia/Scale-UI pull request #8
Opened 2022-02-06 07:49 UTC by rishichourasia

2022-02-06 20:08 UTC, sakshi006 approved these changes
Good to go.

2022-02-06 20:23 UTC, vikrantkode requested changes

2022-02-06 20:23 UTC, vikrantkode commented on Components/Chips/chips.css
> +
use variables while using in colors

2022-02-17 10:09 UTC, rishichourasia commented on Components/Chips/chips.css
> +
Alright Vikrant , thanks

2022-02-17 10:29 UTC, merged